LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := Browser
LOCAL_CERTIFICATE := platform
LOCAL_MULTILIB := both
LOCAL_OVERRIDES_PACKAGES := Jelly
LOCAL_MODULE_TARGET_ARCH := arm arm64 x86 x86_64
src_arch := $(call get-prebuilt-src-arch,$(LOCAL_MODULE_TARGET_ARCH))
LOCAL_SRC_FILES := ChromePublic_$(src_arch).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
include $(BUILD_PREBUILT)
